// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfiznpxdopjdwtuenxqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmaXpucHhkb3BqZHd0dWVueHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODUyNTYsImV4cCI6MjA3Mzk2MTI1Nn0.ibBtVwjDosfQo928zoUH0cLZ03U0pqBLNVyh88MZqQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});